{% set version = "6.12.0" %}

{% set migrating = false %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 84fae3617b70b1219d99a53888d6c404e0e0bc251d13d35dbb84fbf83cf5f894

build:
  number: 0
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} setup.py bdist_wheel
    - cd dist
    - {{ PYTHON }} -m pip install ipykernel-{{ version }}-py3-none-any.whl --no-deps -vv
    - {{ PYTHON }} -m ipykernel install --sys-prefix
    # TODO: this may be needed/desirable at some point
    # - cd {{ RECIPE_DIR }} && {{ PYTHON }} fix_kernelspec.py
  script_env:
    - MIGRATING={{ migrating }}

requirements:
  {% if not win %}
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ipython >=7.23.1                       # [build_platform != target_platform]
    - jupyter_client >=6.1.12                # [build_platform != target_platform]
    - psutil                                 # [build_platform != target_platform]
  {% endif %}
  host:
    - debugpy >=1.0.0
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - pip
    - psutil
    - python
  run:
    - appnope  # [osx]
    - debugpy >=1.0
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - matplotlib-inline >=0.1
    - nest-asyncio
    - packaging
    - psutil
    - python
    - tornado >=6.1
    - traitlets >=5.1.0

test:
  requires:
    - curio  # [not win]
    - flaky
    - numpy
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-timeout
    - trio
    {% if not migrating %}
    - ipyparallel
    - matplotlib-base
    {% endif %}

  imports:
    - ipykernel
  commands:
    - pip check
    - jupyter kernelspec list

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - davidbrochart
