{% set version = "5.1.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 0fc0bf97920d454102168ec2008620066878848fcfca06c22b669696212e292f

build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - python -m ipykernel install --prefix {{ PREFIX }}

requirements:
  host:
    - ipython >=5.0
    - jupyter_client
    - pip
    - python >=3.4
  run:
    - ipython >=5.0
    - jupyter_client
    - python >=3.4
    - tornado >=4.0
    - traitlets >=4.1

test:
  requires:
    - curio  # [unix]
    - matplotlib
    - nose
    - numpy
    - pytest
    - trio
  imports:
    - ipykernel
  commands:
    - jupyter kernelspec list
    - pytest --pyargs ipykernel

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
