{% set version = "5.0.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 3e0ffdf545c0bf80d9dab6523ec6829831408c474772487aeb6eb9f0348b6a1e

build:
  number: 0
  skip: True  # [py2k]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - python -m ipykernel install --prefix $PREFIX  # [not win]
    - python -m ipykernel install --prefix %PREFIX%  # [win]

requirements:
  build:
    - pip
    - python
    - jupyter_client
    - ipython >=4.0
    - tornado >=4.0
  run:
    - python
    - ipython >=5.0
    - traitlets >=4.1
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: https://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - blink1073
    - Carreau
