{% set version = "5.5.5" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: e976751336b51082a89fc2099fb7f96ef20f535837c398df6eab1283c2070884

build:
  number: 0
  skip: true  # [py<34]
  script:
    - {{ PYTHON }} setup.py bdist_wheel
    - cd dist
    - {{ PYTHON }} -m pip install ipykernel-{{ version }}-py3-none-any.whl --no-deps -vv
    - {{ PYTHON }} -m ipykernel install --sys-prefix
    # TODO: this may be needed/desirable at some point
    # - cd {{ RECIPE_DIR }} && {{ PYTHON }} fix_kernelspec.py

requirements:
  {% if not win %}
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ipython >=5.0                          # [build_platform != target_platform]
    - jupyter_client                         # [build_platform != target_platform]
  {% endif %}
  host:
    - ipython >=5.0
    - jupyter_client
    - pip
    - python
  run:
    - ipython >=5.0
    - jupyter_client
    - python
    - tornado >=4.2
    - traitlets >=4.1
    # pyzmq is a run-dep of jupyter_client;
    # temporary pin since v21 breaks pypy
    - pyzmq !=21

test:
  requires:
    - curio
    - flaky
    - ipython
    - nose
    - numpy
    - pytest !=5.3.4
  imports:
    - ipykernel
  commands:
    - jupyter kernelspec list

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
