# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 7.0.0a2
  migrating: false

package:
  name: ipykernel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ipykernel/ipykernel-${{ version }}.tar.gz
  sha256: b3bd996d94ca09012b6df6654a086ddb3a01a40bcd1ad8cc1f5e80b327e0f120

build:
  number: 2
  noarch: python
  script:
    env:
      MIGRATING: ${{ migrating }}
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      - ${{ PYTHON }} -m ipykernel install --sys-prefix

requirements:
  host:
    - hatchling >=1.4
    - pip
    - python ${{ python_min }}.*
    # minimum needed to intall kernelspec
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=8.0.0
    - packaging >=22
    - psutil >=5.7
  run:
    - __${{ noarch_platform }}
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=8.0.0
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio >=1.4
    - packaging >=22
    - psutil >=5.7
    - python >=${{ python_min }}
    - pyzmq >=25
    - tornado >=6.2
    - traitlets >=5.4.0
    - if: noarch_platform == "osx"
      then:
        - appnope

tests:
  - python:
      imports: ipykernel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
      recipe:
        - run_test.py
    requirements:
      run:
        - flaky
        - ipyparallel
        - matplotlib-base
        - numpy
        - pytest >=7.0,<9
        - pytest-asyncio >=0.23.5
        - pytest-cov
        - pytest-timeout
        - python !=${{ python_min }}.*
        - if: not win
          then:
            - curio
    script:
      - jupyter kernelspec list
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  homepage: https://ipython.org
  repository: https://github.com/ipython/ipykernel
  documentation: https://ipykernel.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - davidbrochart
