# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.30.0"
  migrating: "false"
  # versions needed in host/run
  comm_min: "0.1.1"
  debugpy_min: "1.6.5"
  ipython_min: "7.23.1"
  jupyter_client_min: "8.0.0"
  packaging_min: "22"
  psutil_min: "5.7"
  appnope_on_osx: ${{ "appnope >=0.1.2" if osx else "python" }}

package:
  name: ipykernel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ipykernel/ipykernel-${{ version }}.tar.gz
  sha256: b7b808ddb2d261aae2df3a26ff3ff810046e6de3dfbc6f7de8c98ea0a6cb632c

build:
  number: 0
  noarch: python
  script:
    env:
      MIGRATING: ${{ migrating }}
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      - ${{ PYTHON }} -m ipykernel install --sys-prefix

requirements:
  host:
    - hatchling >=1.4
    - pip
    - python ${{ python_min }}.*
    # minimum needed to intall kernelspec
    - comm >=${{ comm_min }}
    - debugpy >=${{ debugpy_min }}
    - ipython >=${{ ipython_min }}
    - jupyter_client >=${{ jupyter_client_min }}
    - packaging >=${{ packaging_min }}
    - psutil >=${{ psutil_min }}
  run:
    - __${{ noarch_platform }}
    - ${{ appnope_on_osx }}
    - comm >=${{ comm_min }}
    - debugpy >=${{ debugpy_min }}
    - ipython >=${{ ipython_min }}
    - jupyter_client >=${{ jupyter_client_min }}
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio >=1.4
    - packaging >=${{ packaging_min }}
    - psutil >=${{ psutil_min }}
    - python >=${{ python_min }}
    - pyzmq >=26
    - tornado >=6.2
    - traitlets >=5.4.0

tests:
  - python:
      imports: ipykernel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
      recipe:
        - run_test.py
    requirements:
      run:
        - flaky
        - ipyparallel
        - matplotlib-base
        - numpy
        - pytest >=7.0,<9
        - pytest-asyncio >=0.23.5
        - pytest-cov
        - pytest-timeout
        - python ${{ python_min }}.*
        - if: unix
          then:
            - curio
    script:
      - jupyter kernelspec list
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  homepage: https://ipython.org
  repository: https://github.com/ipython/ipykernel
  documentation: https://ipython.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - davidbrochart
