bot:
  inspection: hint-all
  abi_migration_branches:
    - 5.x
conda_build:
  pkg_format: "2"
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
  - linux_64
  - osx_64
  - win_64
test: native_and_emulated
